### ISSUE TITLE
这位大哥，麻烦将cloudStorage这个项目删除一下或者设置为私有

### ISSUE THREAD

**Issue by suifengqjn** [feng-ge/ManageSystem#3]
https://github.com/feng-ge/cloudStorage/blob/551d811fdccfeeb1ec0450be81a67b87653adb9f/configs/oss.go

这个文件里面的阿里云参数是我的阿里云参数，我早就删除了，但还是经常收到阿里云的报警电话，取消不掉，所以麻烦帮下忙

**Comment by feng-ge** [comment]
已删



发自我的小米手机
在 fengshi <notifications@github.com>，2020年10月12日 下午2:57写道：

https://github.com/feng-ge/cloudStorage/blob/551d811fdccfeeb1ec0450be81a67b87653adb9f/configs/oss.go

这个文件里面的阿里云参数是我的阿里云参数，我早就删除了，但还是经常收到阿里云的报警电话，取消不掉，所以麻烦帮下忙

**Comment by suifengqjn** [comment]
非常感谢
